name: Wiki backup
on:
  gollum
env:
  TARGET_BRANCH: wiki
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Backup wiki
        uses: Mine02C4/auto_backup_wiki_action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
